In [1]:
import numpy as np
import requests
from functools import reduce
from numpy.random import default_rng


##### activation function: sigmoid
##### cost function: - correct * log (predicted)
## for delta calculation check: https://en.wikipedia.org/wiki/Delta_rule

In [2]:
NUM_HIDDEN_LAYERS = 8
def nonlin(x, deriv=False):
    if (deriv==True):
        return (x*(1-x))

    return 1/(1+np.exp(-x))

with open('words.txt', 'r') as f:
    lines = f.readlines()
    
f.close()

lines = [line[:len(line)-1] for line in lines]
revLines = [line[::-1] for line in lines]

# don't touch above this

In [3]:
max_len = 45 # pneumonoultramicroscopicsilicovolcanoconiosis

# make x and y columns

In [4]:
def makeXY():

    l = len(lines)
    X = np.empty([l, max_len])
    Y = np.empty([l, max_len])
    for ind, word in enumerate(lines):
        
        inArr = np.random.randint(1, 58, (1,max_len)) # ord('z') - 64  = 58
        inArrRev = np.random.randint(1, 58, (1,max_len)) 
        wordLen = len(word)
        for letIndx, let in enumerate(word):
            inArr[0, letIndx] = ord(let) - 64
            inArrRev[0, wordLen-1-letIndx] = ord(let) - 64
        # inArr[letIndx+1:] = 
        X[ind] = inArr
        Y[ind] = inArrRev
    return X, Y

X, Y = makeXY()
X_train = X[0:20000]
Y_train = Y[0:20000]
X_validation = X[20001:20020]
Y_validation = Y[20001:20020]
X_test = X[20020:]
Y_test = X[20020:]

In [9]:
r = np.random.randint(1, 20000)
X[r], Y[r]

(array([33., 35., 52., 41., 46., 47., 44., 41., 52., 37., 22., 37.,  4.,
        45.,  4., 55., 25., 35., 13., 16., 15., 29.,  4.,  7., 18., 25.,
        13., 14., 24., 25., 16., 43., 48.,  9., 32., 42., 49., 15., 53.,
        55., 30., 23., 24., 38., 39.]),
 array([37., 52., 41., 44., 47., 46., 41., 52., 35., 33., 33., 56., 56.,
        28., 47., 56., 21., 48., 25., 49., 16., 44., 48., 32., 19., 14.,
        12., 15., 15., 14.,  7., 20., 52., 10., 10., 16.,  1., 53., 42.,
        54., 13., 36.,  9., 34., 19.]))

# make connections between layers (synapses)

In [ ]:
l = len(lines)
# seed is good for debugging, makes sure we start at
# the same time
np.random.seed(1)
sig = 0.7 # ratio between layers

# synapses (or connections)
# np.random.uniform(low=0.0, high=1.0, size=None)
rng = default_rng()



# the lower limit is set to 1.0 and upper is set to 26.1 because of the best and worst
# cases. In the best case the letter in position i might be the same letter as mid+i.
# In the worst case, the letter might an 'a' whereas it was supposed to be a 'z'
syn0 = rng.uniform(1.0, 26.1, (max_len, int(max_len*sig)))
syn1 = rng.uniform(1.0, 26.1, (int(max_len*sig), int(max_len/sig)))
syn2 = rng.uniform(1.0, 26.1, (int(max_len/sig), int(max_len)))  # large x normal
# synN = np.random.random((int(max_len*sig),max_len))     # this is going to be
import pdb

def forwardBackwardPropagation(x, y, predict=False):
    global syn0, syn1, syn2
    # forward propagation
    l0 = x # 1 x max_len
    l1 = nonlin(np.dot(l0, syn0)) # 1 x normal . normal x small   
    l2 = nonlin(np.dot(l1, syn1)) # 1 x small . small x large
    l3 = nonlin(np.dot(l2, syn2)) # 1 x large . large x normal,   normal = max_len
    
    if predict:
        arr = np.empty([1, max_len])
        for i, el in enumerate(l3):
            if np.abs(el - int(el)) < 0.5:
                v = int(el)
            else:
                v = int(el) + 1
            arr[i] = v + 64
        return arr
    pdb.set_trace()
    l3_error = y * (np.log(l3))   # l3_error: 1 x normal
    l3_delta = l3_error * nonlin(l3, deriv=True)   # l3_delta: 1 x normal
    
    l2_error = l3_delta.dot(syn2.T) # l2_erro: 1 x normal . normal x large = 1 x large
    l2_delta = l2_error * nonlin(l2, deriv=True)  #  l2_delta: 1 x large 
    
    l1_error = l2_delta.dot(syn1.T)  # l1_error: 1 x large . large x small = 1 x small
    l1_delta = l1_error * nonlin(l1, deriv=True)   # l1_delta:  1 x small
    
    large = int(max_len / sig)
    small = int (max_len * sig)
    normal = max_len
    syn2 += np.reshape(l2.T, (large, 1)).dot(np.reshape(l3_delta, (1, normal))  # syn2: large x normal, l2.T: large x 1, l3_delta: 1 x normal
    syn1 += l1.T.dot(l2_delta.T)
    syn0 += l0.T.dot(l1_delta.T)
    
    return

l = len(Y)
for i in np.arange(l):
    forwardBackwardPropagation(X_train[i], Y_train[i])
    
def validate():
    for x, y in zip(X_validation, Y_validation):
        predicted = forwardBackwardPropagation(x, y, True)
        predictedWord = ''.join([chr(el) % 0x110000 for el in predicted])
        actualWord = ''.join([chr(el) % 0x110000 for el in X])
        print(f"actual word: {actualWord}, predicted word: {predictedWord}")
validate()

> <ipython-input-13-c0b10a340e06>(40)forwardBackwardPropagation()
     38         return arr
     39     pdb.set_trace()
---> 40     l3_error = y * (np.log(l3))   # l3_error: 1 x normal
     41     l3_delta = l3_error * nonlin(l3, deriv=True)   # l3_delta: 1 x normal
     42 

ipdb> b 49
Breakpoint 3 at <ipython-input-13-c0b10a340e06>:49
ipdb> r
> <ipython-input-13-c0b10a340e06>(49)forwardBackwardPropagation()
     47     l1_delta = l1_error * nonlin(l1, deriv=True)   # l1_delta:  1 x small
     48 
3--> 49     l3_delta_reshaped = np.reshape(l3_delta, (1, max_len))
     50     syn2 += l2.T.dot(l3_delta_reshaped)  # syn2: large x normal, l2.T: large x 1, l3_delta: 1 x normal
     51     syn1 += l1.T.dot(l2_delta.T)

ipdb> s
--Call--
> <__array_function__ internals>(2)reshape()

ipdb> return
--Return--
array([[0., 0... 0., 0., 0.]])
> <__array_function__ internals>(6)reshape()

ipdb> return
> <ipython-input-13-c0b10a340e06>(50)forwardBackwardPropagation()
     48 
3    49     l3_delta_re

In [47]:
help(np.random.uniform)

Help on built-in function uniform:

uniform(...) method of numpy.random.mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)
    
    Draw samples from a uniform distribution.
    
    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.
    
    .. note::
        New code should use the ``uniform`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less than or equal to high.  The default value is 1.0.
    size : int or tuple o

In [102]:
print(len(X), len(Y))

25487 25487


In [109]:
import logging
import gensim

In [111]:
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
model_vec = gensim.models.KeyedVectors.load_word2vec_format('/Users/prajjwaldangal/Downloads/GoogleNews-vectors-negative300.bin', binary=True)
_VECTOR_SIZE = int(os.environ.get('VECTOR_SIZE', '300'))
_HIDDEN_DIM = int(os.environ.get('HIDDEN_DIM', '500'))
_LEARNING_RATE = float(os.environ.get('LEARNING_RATE', '0.0025'))
_NEPOCH = int(os.environ.get('NEPOCH', '10'))
evaluate_loss_after = 2
vocabulary_size = 25487

_MODEL_FILE = os.environ.get('MODEL_FILE')
vector_size = _VECTOR_SIZE
unknown_token = "UNKNOWN_TOKEN"
sentence_start_token = "SENTENCE_START"
sentence_end_token = "SENTENCE_END"
hidden_dim = _HIDDEN_DIM
learning_rate = _LEARNING_RATE
nepoch = _NEPOCH

2021-05-04 17:22:43,302 : INFO : loading projection weights from /Users/prajjwaldangal/Downloads/GoogleNews-vectors-negative300.bin
2021-05-04 17:23:29,733 : INFO : loaded (3000000, 300) matrix from /Users/prajjwaldangal/Downloads/GoogleNews-vectors-negative300.bin


Reading the input file


In [140]:
class RNNNumpy:
     
    def __init__(self, vector_dim , hidden_dim, label_dim = 6 , bptt_truncate = 6):
        # Assign instance variables
        self.label_dim = label_dim
        self.hidden_dim = hidden_dim
        self.bptt_truncate = bptt_truncate
        self.vector_dim = vector_dim
        # Randomly initialize the network parameters
        self.U = np.random.uniform(-np.sqrt(1./vector_dim), np.sqrt(1./vector_dim), (hidden_dim, vector_dim))
        self.V = np.random.uniform(-np.sqrt(1./hidden_dim), np.sqrt(1./hidden_dim), (label_dim, hidden_dim))
        self.W = np.random.uniform(-np.sqrt(1./hidden_dim), np.sqrt(1./hidden_dim), (hidden_dim, hidden_dim))

def forward_propagation(self, x):
    # import pdb; pdb.set_trace()

    # The total number of time steps
    T = len(x)
    # During forward propagation we save all hidden states in s because need them later.
    # We add one additional element for the initial hidden, which we set to 0
    s = np.zeros((T + 1, self.hidden_dim))
    s[-1] = np.zeros(self.hidden_dim)
    # The outputs at each time step. Again, we save them for later.
    o = np.zeros((T+1, self.label_dim))
    # For each time step...
    for t in np.arange(T):
        X_i = x[t]
        s[t] = np.tanh(self.U.dot(X_i) + self.W.dot(s[t-1]))
    o = softmax(self.V.dot(s[-2]))
    return [o, s]
RNNNumpy.forward_propagation = forward_propagation

def predict(self, x):
    # Perform forward propagation and return index of the highest score
    o, s = self.forward_propagation(x)
    return np.argmax(o, axis=0)
 
RNNNumpy.predict = predict


def calculate_total_loss(self, x, y):
    L = 0.0
    # For each sentence...
    for i in np.arange(len(y)):
        o, s = self.forward_propagation(x[i])
        # We only care about our prediction of the "correct" words
        correct_word_predictions = o[y[i]]
        # Add to the loss based on how off we were
        L += -1.0 * (np.log(correct_word_predictions))
    return L
 
def calculate_loss(self, x, y):
    # Divide the total loss by the number of training examples
    # y -> all y_train[i]
    N = len(y)
    return self.calculate_total_loss(x,y)/N
 
RNNNumpy.calculate_total_loss = calculate_total_loss
RNNNumpy.calculate_loss = calculate_loss

def bptt(self, x, y):
    T = len(x)
    # Perform forward propagation
    o, s = self.forward_propagation(x)
    # We accumulate the gradients in these variables
    dLdU = np.zeros(self.U.shape)
    dLdV = np.zeros(self.V.shape)
    dLdW = np.zeros(self.W.shape)
    delta_o = o
    delta_o[y] -= 1.
    # For each output backwards...
    dLdV += np.outer(delta_o, s[T-1].T)
    # Initial delta calculation
    delta_t = self.V.T.dot(delta_o) * (1 - (s[-1] ** 2))
    # Backpropagation through time (for at most self.bptt_truncate steps)
    for bptt_step in np.arange(max(0, (T-1)-self.bptt_truncate), (T-1)+1)[::-1]:
        #print "Backpropagation step t=%d bptt step=%d " % (t, bptt_step)
        dLdW += np.outer(delta_t, s[bptt_step-1])     
        X_j = x[bptt_step]
        dLdU += np.outer(delta_t, X_j)   
        # Update delta for next step
        delta_t = self.W.T.dot(delta_t) * (1 - s[bptt_step-1] ** 2)
    return [dLdU, dLdV, dLdW]
 
RNNNumpy.bptt = bptt


# Performs one step of SGD.
def numpy_sgd_step(self, x, y, learning_rate):
    # Calculate the gradients
    dLdU, dLdV, dLdW = self.bptt(x, y)
    # Change parameters according to gradients and learning rate
    self.U -= learning_rate * dLdU
    self.V -= learning_rate * dLdV
    self.W -= learning_rate * dLdW
 
RNNNumpy.sgd_step = numpy_sgd_step


# Outer SGD Loop
# - model: The RNN model instance
# - X_train: The training data set
# - y_train: The training data labels
# - learning_rate: Initial learning rate for SGD
# - nepoch: Number of times to iterate through the complete dataset
# - evaluate_loss_after: Evaluate the loss after this many epochs
def train_with_sgd(model, X_train, y_train, learning_rate, nepoch, evaluate_loss_after):
    # We keep track of the losses so we can plot them later
    losses = []
    num_examples_seen = 0
    print ("There is going to be ", nepoch, " epoches")
    for epoch in range(nepoch):
        if (epoch % evaluate_loss_after == 0):
            loss = model.calculate_loss(X_train, y_train)
            losses.append((num_examples_seen, loss))
            time = datetime.now().strftime('%Y-%m-%d-%H-%M-%S')
            print ("%s: Loss after num_examples_seen=%d epoch=%d: %f" % (time, num_examples_seen, epoch, loss))
            # Adjust the learning rate if loss increases
            if (len(losses) > 1 and losses[-1][1] > losses[-2][1]):
                learning_rate = learning_rate * 0.5  
                print ("Setting learning rate to %f" % learning_rate)
            sys.stdout.flush()
        # For each training example...
        
        for i in range(len(y_train)):
            # One SGD step
            model.sgd_step(X_train[i], y_train[i], learning_rate)
            num_examples_seen += 1
    filename11 = 'numpy_model.sav'
    pickle.dump(model, open(filename11, 'wb'))
model = RNNNumpy(vector_size,hidden_dim)

In [ ]:
train_with_sgd(model, X_train, y_train, learning_rate, nepoch, evaluate_loss_after)